# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# coding: utf-8

Label.create(label_name:'ユニバーサルミュージック')
Label.create(label_name:'rhythm zone')
Label.create(label_name:'ARC')
Label.create(label_name:'アートハートレコード')
Label.create(label_name:'日本コロムビア')
Label.create(label_name:'エイベックス')
Label.create(label_name:"よしもとミュージック")
Label.create(label_name:"Virgin Music(JPN)")
Label.create(label_name:"トイズファクトリー")
Label.create(label_name:"Buzzic")
Label.create(label_name:"ブシロードミュージック")
Label.create(label_name:"インディーズ・メーカー")
Label.create(label_name:"zetima")
Label.create(label_name:"キングレコード")
Label.create(label_name:"SPACE SHOWER MUSIC")

Genre.create(genre_name:'J-Pop')
Genre.create(genre_name:'Rock')
Genre.create(genre_name:'Dance')
Genre.create(genre_name:'Jazz')
Genre.create(genre_name:'演歌')
Genre.create(genre_name:'インディーズ')

Artist.create(artist_name:"RADIO FISH")
Artist.create(artist_name:"GLIM SPANKY")
Artist.create(artist_name:"BRAHMAN")
Artist.create(artist_name:"Gendy 100km")
Artist.create(artist_name:"新田恵海")
Artist.create(artist_name:"宮沢昭")
Artist.create(artist_name:"MOROHA")
Artist.create(artist_name:"MIHIRO")
Artist.create(artist_name:"小沢あきこ")
Artist.create(artist_name:"美川憲一")
Artist.create(artist_name:"岡田しのぶ")
Artist.create(artist_name:"CASANOVA FISH")
Artist.create(artist_name:"The Daybreaker")
Artist.create(artist_name:"高橋友里")
Artist.create(artist_name:"モーニング娘'18")
Artist.create(artist_name:"宮沢昭")
Artist.create(artist_name:"鈴木良雄")

Cd.create(name:"NEWTON", price:"1650", stock:"10", sale_status:"販売中", artist_id:"1", label_id:"9", genre_id:"3", description:"『NEWTON』(ニュートン) は、日本のお笑いコンビ・オリエンタルラジオが率いる音楽グループ、RADIO FISHの3枚目のスタジオ・アルバム。2019年1月9日によしもとミュージックエンタテインメントより配信リリース。", image_id:"")
Cd.create(name:"WORLD IS MINE", stock:"10", price:"2700", sale_status:"販売中", artist_id:"1", label_id:"9", genre_id:"3", description:"「PERFECT HUMAN」のコンポーザー“JUVENILE“の新曲「GOLDEN TOWER」は、 ゲストボーカリストに実力派シンガー“當山みれい“を迎え、これまでとは違う広がりを見せ、 さらには話題のテクノユニット“80KIDZ“との新曲「東京大革命」では、藤森とのラップバトルが衝撃的です。", image_id:"")
Cd.create(name:"LOOKING FOR THE MAGIC", price:"2800", stock:"10", sale_status:"販売中", artist_id:"2", label_id:"10", genre_id:"2", description:"“至上のロック”をかき鳴らす4thアルバム『LOOKING FOR THE MAGIC』リリース！今アルバムには、『不能犯』（主演：松坂桃李）の主題歌で、iTunes総合チャートでも1位を獲得した、GLIM SPANKYの代表曲ともいえる「愚か者たち」を収録。", image_id:"" )
Cd.create(name:"BIZARRE CARNIVAL", price:"2800", stock:"10", sale_status:"販売中", artist_id:"2", label_id:"10", genre_id:"2", description:"2017年は海外ライブも大成功し、ライブ面でもステップアップし各所大旋風を巻き起こしつつあるGLIM SPANKY。ネクストレベルへ上るべく、GLIM SPANKY節の疾走感のあるライブロックチューンアルバムを目指します。", image_id:"")
Cd.create(name:"尽未来際", price:"3000", stock:"10", sale_status:"販売中", artist_id:"3", label_id:"11", genre_id:"2", description:"今年、結成20周年を迎えるBRAHMAN。 バンド結成以来、4人は一貫して独立独歩の活動を続け、数々の名曲と激演で多くのパンクスたちの胸を震わせてきた。そんな名曲群が結集した作品が登場！「尽未来際」というタイトル通り、彼らを新たなる未来へと導く。", image_id:"")
Cd.create(name:"梵唄 -bonbai-", price:"2800", stock:"10", sale_status:"販売中", artist_id:"3", label_id:"11", genre_id:"2", description:"激動の時代を駆け抜け、ジャンルの壁を飛び越え、 シーンにおける存在感をさらに高めているBRAHMAN。5年ぶりとなるフルアルバムで真の境地へ到達。過去最大級の重みと力強さで、数々の名曲と、己の生き様を４人が叩きつける。", image_id:"")
Cd.create(name:"感恩報謝", price:"2100", stock:"10", sale_status:"販売中", artist_id:"4", label_id:"12", genre_id:"1", description:"2012年に“Gendy 100km”としてデビューした長野県出身の男性ソロ・アーティストによるアルバム。", image_id:"")
Cd.create(name:"EMUSIC 32 -meets you-", price:"2400", stock:"10", sale_status:"販売中", artist_id:"5",label_id:"12", genre_id:"1", description:"『EMUSIC 32 -meets you-』は、新田恵海の2枚目のスタジオ・アルバムである。2018年5月16日にブシロードミュージック内のプライベートレーベルであるemitsunレーベルから発売された。本作のリード曲「君に咲く愛のうた」の作詞はZAQ、作曲・編曲は松坂康司が担当した。", image_id:"")
Cd.create(name:"BULL TROUT(いわな)", price:"2333", stock:"10", sale_status:"販売中", artist_id:"6", label_id:"13", genre_id:"4", description:"長らく廃盤だった和ジャズの大名盤、遂に復刻!!和ジャズの中で精神性の高さを求めるならば、なんといってもこの「いわな」でしょう。冬頃のリリースを予定しておりましたが、様々な方より復刻希望のリクエストがあったため、リリースを早めました。", image_id:"")
Cd.create(name:"山女魚", price:"1620", stock:"10", sale_status:"販売中", artist_id:"6", label_id:"5", genre_id:"4", description:"キング・レコードが誇る日本のジャズ名盤が最新リマスタリングで復活!現在入手困難となっている1950年代から80年代までの伝説的名盤を高音質SHM-CDでお届けする“KING LEGENDARY JAZZ COLLECTION 50”シリーズ。本作は、日本ジャズ史における最高のテナー・サックス奏者・宮沢昭が放つモダン・ジャズの歴史的作品。", image_id:"")

Disc.create(disc_number:"1", cd_id:"1")
Disc.create(disc_number:"1", cd_id:"2")
Disc.create(disc_number:"1", cd_id:"3")
Disc.create(disc_number:"1", cd_id:"4")
Disc.create(disc_number:"1", cd_id:"5")
Disc.create(disc_number:"2", cd_id:"5")
Disc.create(disc_number:"1", cd_id:"6")
Disc.create(disc_number:"1", cd_id:"7")
Disc.create(disc_number:"1", cd_id:"8")
Disc.create(disc_number:"1", cd_id:"9")
Disc.create(disc_number:"1", cd_id:"10")


Song.create(song_name:"Gamber", song_number:"1", disc_id:"1")
Song.create(song_name:"No.55", song_number:"2", disc_id:"1")
Song.create(song_name:"また逢える日まで", song_number:"3", disc_id:"1")
Song.create(song_name:"東京大革命", song_number:"4", disc_id:"1")
Song.create(song_name:"GOLDEN TOWER", song_number:"5", disc_id:"1")
Song.create(song_name:"INVISIBLE EMPEROR", song_number:"6", disc_id:"1")
Song.create(song_name:"NEW GOD", song_number:"7", disc_id:"1")
Song.create(song_name:"BURNING FESTIVAL", song_number:"8", disc_id:"1")
Song.create(song_name:"ULTRA TIGER", song_number:"1", disc_id:"2")
Song.create(song_name:"GOLDEN TOWER", song_number:"2", disc_id:"2")
Song.create(song_name:"東京大革命", song_number:"3", disc_id:"2")
Song.create(song_name:"NKT34", song_number:"4", disc_id:"2")
Song.create(song_name:"INVISIBLE EMPEROR", song_number:"5", disc_id:"2")
Song.create(song_name:"あの日見た神様の名前を思い出していつかきっと泣いてしまう", song_number:"6", disc_id:"2")
Song.create(song_name:"黄金時代", song_number:"7", disc_id:"2")
Song.create(song_name:"WONDERLAND", song_number:"8", disc_id:"2")
Song.create(song_name:"ワンチャンCOCO夏☆物語", song_number:"9", disc_id:"2")
Song.create(song_name:"MIND BEACH", song_number:"10", disc_id:"2")
Song.create(song_name:"さよなら", song_number:"11", disc_id:"2")
Song.create(song_name:"PERFECT HUMAN", song_number:"12", disc_id:"2")
Song.create(song_name:"PERFECT HUMAN [m-flo☆Taku Remix]", song_number:"13", disc_id:"2")
Song.create(song_name:"4 Dimensional Desert", song_number:"1", disc_id:"3")
Song.create(song_name:"Love Is There", song_number:"2", disc_id:"3")
Song.create(song_name:"TV Show", song_number:"3", disc_id:"3")
Song.create(song_name:"ハートが冷める前に", song_number:"4", disc_id:"3")
Song.create(song_name:"The Flowers", song_number:"5", disc_id:"3")
Song.create(song_name:"In the air", song_number:"6", disc_id:"3")
Song.create(song_name:"愚か者たち", song_number:"7", disc_id:"3")
Song.create(song_name:"Hello Sunshine", song_number:"8", disc_id:"3")
Song.create(song_name:"All Of Us", song_number:"9", disc_id:"3")
Song.create(song_name:"To The Music", song_number:"10", disc_id:"3")
Song.create(song_name:"Looking For The Magic", song_number:"11", disc_id:"3")
Song.create(song_name:"THE WALL", song_number:"1", disc_id:"3")
Song.create(song_name:"BIZARRE CARNIVAL", song_number:"2", disc_id:"3")
Song.create(song_name:"The Trip", song_number:"3", disc_id:"3")
Song.create(song_name:"吹き抜く風のように", song_number:"4", disc_id:"3")
Song.create(song_name:"Velvet Theater", song_number:"5", disc_id:"3")
Song.create(song_name:"END ROLL", song_number:"6", disc_id:"3")
Song.create(song_name:"Sonntag", song_number:"7", disc_id:"3")
Song.create(song_name:"ビートニクス", song_number:"8", disc_id:"3")
Song.create(song_name:"美しい棘", song_number:"9", disc_id:"3")
Song.create(song_name:"白昼夢", song_number:"10", disc_id:"3")
Song.create(song_name:"アイスタンドアローン", song_number:"11", disc_id:"3")
Song.create(song_name:"TONGFARR", song_number:"1", disc_id:"4")
Song.create(song_name:"FOR ONE’S LIFE", song_number:"2", disc_id:"4")
Song.create(song_name:"SEE OFF", song_number:"3", disc_id:"4")
Song.create(song_name:"GOIN’ DOWN", song_number:"4", disc_id:"4")
Song.create(song_name:"GREAT HELP", song_number:"5", disc_id:"4")
Song.create(song_name:"BASIS", song_number:"6", disc_id:"4")
Song.create(song_name:"SHADOW PLAY", song_number:"7", disc_id:"4")
Song.create(song_name:"PLASTIC SMILE", song_number:"8", disc_id:"4")
Song.create(song_name:"BOX", song_number:"9", disc_id:"4")
Song.create(song_name:"BEYOND THE MOUNTAIN", song_number:"10", disc_id:"4")
Song.create(song_name:"初期衝動", song_number:"1", disc_id:"5")
Song.create(song_name:"THE ONLY WAY", song_number:"2", disc_id:"5")
Song.create(song_name:"賽の河原", song_number:"3", disc_id:"5")
Song.create(song_name:"THE VOID", song_number:"4", disc_id:"5")
Song.create(song_name:"露命", song_number:"5", disc_id:"5")
Song.create(song_name:"EPIGRAM", song_number:"6", disc_id:"5")
Song.create(song_name:"SPECULATION", song_number:"7", disc_id:"5")
Song.create(song_name:"其限", song_number:"8", disc_id:"5")
Song.create(song_name:"鼎の問", song_number:"9", disc_id:"5")
Song.create(song_name:"A WHITE DEEP MORNING", song_number:"10", disc_id:"5")
Song.create(song_name:"真善美", song_number:"1", disc_id:"6")
Song.create(song_name:"雷同", song_number:"2", disc_id:"6")
Song.create(song_name:"EVERMORE FOREVER MORE", song_number:"3", disc_id:"6")
Song.create(song_name:"AFTER-SENSATION", song_number:"4", disc_id:"6")
Song.create(song_name:"其限", song_number:"5", disc_id:"6")
Song.create(song_name:"今夜", song_number:"6", disc_id:"6")
Song.create(song_name:"守破離", song_number:"7", disc_id:"6")
Song.create(song_name:"怒涛の彼方", song_number:"8", disc_id:"6")
Song.create(song_name:"不倶戴天", song_number:"9", disc_id:"6")
Song.create(song_name:"ナミノウタゲ", song_number:"10", disc_id:"6")
Song.create(song_name:"天馬空を行く", song_number:"11", disc_id:"6")
Song.create(song_name:"満月の夕", song_number:"12", disc_id:"6")
Song.create(song_name:"感恩報謝", song_number:"1", disc_id:"7")
Song.create(song_name:"with you", song_number:"2", disc_id:"7")
Song.create(song_name:"魔法のチカラ", song_number:"3", disc_id:"7")
Song.create(song_name:"相思相愛", song_number:"4", disc_id:"7")
Song.create(song_name:"たいせつなひと", song_number:"5", disc_id:"7")
Song.create(song_name:"タンス feat.末延麻裕子", song_number:"6", disc_id:"7")
Song.create(song_name:"ありがとう。ふるさと", song_number:"7", disc_id:"7")
Song.create(song_name:"奇跡のひかり", song_number:"8", disc_id:"7")
Song.create(song_name:"かけがえのない宝物 feat.丸本莉子", song_number:"9", disc_id:"7")
Song.create(song_name:"素晴らしい未来の為に", song_number:"10", disc_id:"7")
Song.create(song_name:"32 -meets you-", song_number:"1", disc_id:"8")
Song.create(song_name:"君に咲く愛のうた", song_number:"2", disc_id:"8")
Song.create(song_name:"コイスルマチカド", song_number:"3", disc_id:"8")
Song.create(song_name:"Colorful Parade", song_number:"4", disc_id:"8")
Song.create(song_name:"In the Ring", song_number:"5", disc_id:"8")
Song.create(song_name:"マスカレイド", song_number:"6", disc_id:"8")
Song.create(song_name:"勿忘草", song_number:"7", disc_id:"8")
Song.create(song_name:"Bon Voyage!", song_number:"8", disc_id:"8")
Song.create(song_name:"Baby Call My Name", song_number:"9", disc_id:"8")
Song.create(song_name:"my youth", song_number:"10", disc_id:"8")
Song.create(song_name:"UNITED", song_number:"11", disc_id:"8")
Song.create(song_name:"いわな", song_number:"1", disc_id:"9")
Song.create(song_name:"河ます", song_number:"2", disc_id:"9")
Song.create(song_name:"あゆ", song_number:"3", disc_id:"9")
Song.create(song_name:"虹ます", song_number:"4", disc_id:"9")
Song.create(song_name:"山女魚", song_number:"1", disc_id:"10")
Song.create(song_name:"メモリーズ・スルー・シック・グラセス", song_number:"2", disc_id:"10")
Song.create(song_name:"フライ・キャスティング", song_number:"3", disc_id:"10")
Song.create(song_name:"ライク・サムワン・イン・ラヴ", song_number:"4", disc_id:"10")
Song.create(song_name:"アウト・オブ・ノーホエア", song_number:"5", disc_id:"10")
Song.create(song_name:"香わしきたそがれ", song_number:"6", disc_id:"10")
Song.create(song_name:"ライク・ソニー", song_number:"7", disc_id:"10")


client = Client.new(:last_name => '相葉', :first_name => '雅紀', :last_name_kana => 'アイバ', :first_name_kana => 'マサキ', :email => 'aiba@gmail.com', :address => '千葉県船橋市', :post_code => '100-1000', :telephone => '100-1000-1000', :password => 'arashi')
client.save!
client = Client.new(:last_name => '松本', :first_name => '潤也', :last_name_kana => 'マツモト', :first_name_kana => 'ジュンヤ', :email => 'matsu@gmail.com', :address => '東京都練馬区', :post_code => '100-1000', :telephone => '100-1000-1000', :password => 'arashi')
client.save!
client = Client.new(:last_name => '二宮', :first_name => '和也', :last_name_kana => 'ニノミヤ', :first_name_kana => 'カズヤ', :email => 'nino@gmail.com', :address => '東京都江戸川区', :post_code => '100-1000', :telephone => '100-1000-1000', :password => 'arashi')
client.save!
client = Client.new(:last_name => '大野', :first_name => '智史', :last_name_kana => 'オオノ', :first_name_kana => 'サトシ', :email => 'oono@gmail.com', :address => '東京都渋谷区', :post_code => '100-1000', :telephone => '100-1000-1000', :password => 'arashi')
client.save!
client = Client.new(:last_name => '櫻井', :first_name => '翔也', :last_name_kana => 'サクライ', :first_name_kana => 'ショウヤ', :email => 'saku@gmail.com', :address => '東京都中央区', :post_code => '100-1000', :telephone => '100-1000-1000', :password => 'arashi')
client.save!

admin = Admin.new(:email => 'nagareco@gmail.com', :password => 'nagareco')
admin.save!

Address.create(:last_name => '相葉', :first_name => '雅紀', :sub_post_code => '100-1000', :sub_address => '東京都八王子市', :client_id => '1')
Address.create(:last_name => 'wents', :first_name => 'eji', :sub_post_code => '100-1000', :sub_address => '沖縄県沖縄市', :client_id => '3')
Address.create(:last_name => '櫻井', :first_name => '翔也', :sub_post_code => '100-1000', :sub_address => '神奈川県鎌倉市', :client_id => '5')
Address.create(:last_name => '長瀬', :first_name => '智也', :sub_post_code => '100-1000', :sub_address => '北海道函館市', :client_id => '5')
Address.create(:last_name => '国分', :first_name => '太一', :sub_post_code => '100-1000', :sub_address => '東京都練馬区', :client_id => '5')
